version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Setup Node.js via nvm
          command: |
            # When `.nvmrc` exists, `nvm.sh` fails. So disable auto-install temporarily via `--no-use` option.
            curl --silent -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo 'source "$NVM_DIR/nvm.sh"' >> $BASH_ENV 
            source $BASH_ENV
            nvm install --latest-npm --no-progress
            nvm alias default
            node -v && npm -v
            sed -i -e 's/ --no-use//' $BASH_ENV # Cleanup `--no-use` option
      - run:
          name: Verify
          command: node -v && npm -v
